#!/bin/sh
# ** (c) 2018 vbettag - install for Kopano4s in Docker container
echo "$(date '+%Y.%m.%d-%H:%M:%S') postuninst" >> /tmp/inst.log
# ** get common procedures, settings, tags and download urls
. "$(dirname $0)"/common
. "$ETC_PATH"/package.cfg
DROP_SOFTLINKS
DROP_USER_DATABASE
DROP_DOCKER
DROP_MYSQL_TUNING
# now delete the etc area to avoid it left orphaned
rm -R /usr/syno/etc/packages/Kopano4s
exit 0
