#!/bin/sh
# ** (c) 2018 vbettag - install for Kopano4Syno in Docker container
echo "$(date '+%Y.%m.%d-%H:%M:%S') preinst" > /tmp/inst.log
# ** get common procedures, settings, tags and download urls
. "$(dirname $0)"/common
# ** install only modus
if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]
then
	# ** verify conflicting container and downloads available for building container otherwise exit
	PKG_PRE_CHECK
else
	if [ -e $ETC_PATH/package.cfg ]
	then 
		. "$ETC_PATH"/package.cfg
	fi
fi
# ** install and upgrade: download the latest image
# download pre check includes get_ver_tag
DOWNL_PRE_CHECK
K4S_IMAGE="tosoboso/kopano4s"
if [ "$PKGWIZ_BUILD" != "true" ] && ! docker images | grep $K4S_IMAGE | grep -q $VER_TAG
then
	DOCKER_PATH="$(synoshare --get docker | grep $"\t Path" | sed "s/.*\[\(.*\)].*/\1/")"
	SPIN_HELPER_TIMEOUT
	GET_K4S_SIZE
	# ** usage:/var/packages/Docker/target/tool/helper JOB: image_name image_tag image_path image_download_size_mb
	# ** SYNOPKG_PKG_PROGRESS_PATH = /tmp/install_progress_Kopano4s will be needed to show and run aka only in GUI mode
	NOTIFY_MESSAGE "Pulling k4s Docker image (${K4S_SIZE}M ~2-3m; time-out: 4m). Please ignore potential install errors: this is a Synology package installer time-out.."
	if ! /var/packages/Docker/target/tool/helper $K4S_IMAGE $VER_TAG $DOCKER_PATH/k4s-$VER_TAG.tar.xz $K4S_SIZE
	then
		LOG_MESSAGE "Failed pulling $K4S_IMAGE $VER_TAG"
	fi
fi
exit 0
