#!/bin/sh
# ** get common procedures, settings, tags and download urls
. "$(dirname $0)"/common
if [ ! -e "$ETC_PATH"/package.cfg ] ; then touch "$ETC_PATH"/package.cfg ; fi
. "$ETC_PATH"/package.cfg
if [ ! -n "$INSTALL_STATE" ] || [ "$INSTALL_STATE" != "completed" ]
then
	GUI_MESSAGE "No upgrade to previously uncompleted or legacy install. Please remove and install again. "
	exit 1
fi
# ** backup install-log & etc
SAVE_LOG_ETC
exit 0

